"""add meetups table

Revision ID: 0035
Revises: 0034
Create Date: 2026-09-08 23:44:17.907388
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0035"
down_revision: str | None = "0034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetups",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("channel_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'ended')", name="meetups_status_check"),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "meetups_channel",
        "meetups",
        ["channel_id"],
        unique=False,
        postgresql_where=sa.text("channel_id IS NOT NULL"),
    )
    op.create_index(
        "meetups_workspace_recent",
        "meetups",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("meetups_workspace_recent", table_name="meetups")
    op.drop_index(
        "meetups_channel", table_name="meetups", postgresql_where=sa.text("channel_id IS NOT NULL")
    )
    op.drop_table("meetups")
    # ### end Alembic commands ###
