#!/usr/bin/env node
/**
 * Write the recent history into the client, so the "What's new" page can show it on a
 * host that does not ship a repository.
 *
 * `vite.config.ts` already asks git at build time, and where that works it wins — it is
 * exact, and it includes the commit being built. But the deploy here builds from an
 * exported source tree with no `.git` in the context, so on the machine that matters git
 * answers nothing and the page would have nothing to show. This is the fallback: run
 * `pnpm stamp` before committing and the history travels as source.
 *
 * The file it writes is *one commit behind* by construction — a commit cannot contain its
 * own hash — which is why the page calls the section "recent commits" rather than "the
 * commits in this build", and why the build card takes the running commit from the
 * server instead.
 *
 * Writes nothing at all when git cannot answer. Overwriting a good file with an empty one
 * because this happened to run somewhere without a repository is the one failure that
 * would be worse than not running.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'apps', 'web', 'src', 'lib', 'commits.generated.ts');
const LIMIT = 60;

function git(args) {
  try {
    return execFileSync('git', args, {
      cwd: join(HERE, '..'),
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

function repoWebUrl() {
  const origin = git(['config', '--get', 'remote.origin.url']);
  if (!origin) return '';
  const ssh = /^git@([^:]+):(.+?)(?:\.git)?$/.exec(origin);
  if (ssh) return `https://${ssh[1]}/${ssh[2]}`;
  const https = /^https?:\/\/(?:[^@]+@)?(.+?)(?:\.git)?$/.exec(origin);
  if (https) return `https://${https[1]}`;
  return '';
}

// Unit separator between fields, record separator between commits: a subject can contain
// anything a person can type, so the delimiter has to be something a keyboard does not.
const raw = git([
  'log',
  `-${LIMIT}`,
  '--no-merges',
  '--pretty=format:%H%x1f%h%x1f%s%x1f%aI%x1f%an%x1e',
]);

if (!raw) {
  console.log('stamp-commits: git said nothing; leaving the checked-in history alone.');
  process.exit(0);
}

const commits = raw
  .split('\x1e')
  .map((record) => record.trim())
  .filter(Boolean)
  .map((record) => {
    const [sha = '', shortSha = '', subject = '', date = '', author = ''] = record.split('\x1f');
    return { sha, shortSha, subject, date, author };
  })
  .filter((commit) => commit.sha !== '');

const body = `/** Generated by \`pnpm stamp\`. Do not edit — see \`scripts/stamp-commits.mjs\`.
 *
 * The recent history, as source, so the "What's new" page can show it on a host that
 * builds from an exported tree with no repository in it. One commit behind by
 * construction: a commit cannot contain its own hash.
 */

import type { BuildCommit } from './buildInfo.ts';

export const GENERATED_REPO_URL = ${JSON.stringify(repoWebUrl())};

export const GENERATED_COMMITS: readonly BuildCommit[] = ${JSON.stringify(commits, null, 2)};
`;

let existing = '';
try {
  existing = readFileSync(OUT, 'utf8');
} catch {
  // First run.
}

if (existing === body) {
  console.log('stamp-commits: already current.');
} else {
  writeFileSync(OUT, body);
  console.log(`stamp-commits: wrote ${commits.length} commits.`);
}
