/** Generated by `pnpm stamp`. Do not edit — see `scripts/stamp-commits.mjs`.
 *
 * The recent history, as source, so the "What's new" page can show it on a host that
 * builds from an exported tree with no repository in it. One commit behind by
 * construction: a commit cannot contain its own hash.
 */

import type { BuildCommit } from './buildInfo.ts';

export const GENERATED_REPO_URL = "https://github.com/magnetoid/blob";

export const GENERATED_COMMITS: readonly BuildCommit[] = [
  {
    "sha": "d24890966e76aaeaffa0ea77f22756ebecaee6cc",
    "shortSha": "d248909",
    "subject": "Refresh the map for the seven commits before it",
    "date": "2026-09-12T14:24:09+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "17af2e5ef6b601d8835083dbf78b7a7fc79c3038",
    "shortSha": "17af2e5",
    "subject": "Say who is in the room, and which of them are agents",
    "date": "2026-09-12T14:20:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d57c5063564af2f2a597fee9113c6512022d409d",
    "shortSha": "d57c506",
    "subject": "Give a narrow screen the whole width",
    "date": "2026-09-12T14:19:06+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "322a45e64ef8c84bcfca47e2c38a4d6f004fb81a",
    "shortSha": "322a45e",
    "subject": "Let an agent post where it is sent, behind a grant of its own",
    "date": "2026-09-12T14:17:05+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "78686115786a9f312963a36bac48b04984de695c",
    "shortSha": "7868611",
    "subject": "Answer a DM that names nobody",
    "date": "2026-09-12T14:15:55+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "daa7153ddd763f9b58f1544d5c04f7dfd8afed2c",
    "shortSha": "daa7153",
    "subject": "Read an empty setting as no setting",
    "date": "2026-09-12T14:14:13+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2af6ed2dd3da59be5c4d2aab73966b4c25b68f10",
    "shortSha": "2af6ed2",
    "subject": "Reach DeepSeek at its own address",
    "date": "2026-09-12T14:12:35+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "856199d599a751c8c628839ad71dbfbecf446aef",
    "shortSha": "856199d",
    "subject": "Run the suite with no model, whatever .env says",
    "date": "2026-09-12T14:10:45+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "047baf4dccf589e7b605b9f304c60afb915538b4",
    "shortSha": "047baf4",
    "subject": "Pull MinIO from a registry that still has it",
    "date": "2026-09-12T01:43:18+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d317523705a9363dc02a5b7643604ac5ecac76c6",
    "shortSha": "d317523",
    "subject": "Put the claim beside the sign-in",
    "date": "2026-09-12T01:21:21+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "05ca96b77d8b50e8b80d66e4fb81dd7989a06c02",
    "shortSha": "05ca96b",
    "subject": "Let a citation look like what it points at",
    "date": "2026-09-11T23:58:02+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "aa730e2d075561c7733e74e817623b0eb055d2f8",
    "shortSha": "aa730e2",
    "subject": "Mark a summary a model wrote as one",
    "date": "2026-09-11T23:54:05+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "64055f29f4565b5f283910f7a91ecd525c15c14e",
    "shortSha": "64055f2",
    "subject": "Give agents a colour of their own",
    "date": "2026-09-11T23:43:31+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "3f15c945c63a1e32ebfa991eb31d5b1da2f4326f",
    "shortSha": "3f15c94",
    "subject": "Drop the last two settings of a thing we never used",
    "date": "2026-09-11T19:31:39+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7d440258817aba76cf3bdfd181754be00434edbb",
    "shortSha": "7d44025",
    "subject": "Cover the room the question is actually asked in",
    "date": "2026-09-11T18:51:07+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5f5d9cc82b1ec9befff5be9ada6e28a922225f59",
    "shortSha": "5f5d9cc",
    "subject": "Let the agent say who is in the room",
    "date": "2026-09-11T18:50:01+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e5b23e0ee88a89ae87067f3c392680dd214902e4",
    "shortSha": "e5b23e0",
    "subject": "Stamp the history What's new shows",
    "date": "2026-09-11T17:44:27+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "bf8fabd028e8a091dc3c61b13c3fe8e2fd08e050",
    "shortSha": "bf8fabd",
    "subject": "Give the consoles one shape, and the admin pages one home each",
    "date": "2026-09-11T17:43:04+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "709ae622f7e4fa591d682aa129ad2a8462fb4bb8",
    "shortSha": "709ae62",
    "subject": "Let @Blob read the workspace, as the person who asked",
    "date": "2026-09-11T17:42:16+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b87288fc74029a47bc25af7ebd353629a732eb1c",
    "shortSha": "b87288f",
    "subject": "Let the model layer run tools, so an agent can act",
    "date": "2026-09-11T17:41:51+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b2ebb5363cfe86be6d54c28e8cfd057207267394",
    "shortSha": "b2ebb53",
    "subject": "Stop an unconfigured media server from keeping chat down",
    "date": "2026-09-11T14:24:44+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5e1485608e4032f4995250d5aa8b6d09b7dd53f4",
    "shortSha": "5e14856",
    "subject": "Make meetups reachable and give them their channel's access",
    "date": "2026-09-11T13:58:56+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "c30b3ecc2ea1ae3c616bb2bf2504cd750fd5318a",
    "shortSha": "c30b3ec",
    "subject": "Quote LiveKit's key pair, and stop generating a domain for it",
    "date": "2026-09-11T05:24:25+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1e11f55aba93d78af846c9d13d2b01fa93bebdc8",
    "shortSha": "1e11f55",
    "subject": "Run LiveKit beside Blob, so meetups have somewhere to connect",
    "date": "2026-09-11T05:02:47+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "dea137ba0c2ab691a33c636ffbddd6fd6aea5177",
    "shortSha": "dea137b",
    "subject": "Bring CLAUDE.md up to date with the agentic surface",
    "date": "2026-09-11T03:51:49+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7fc07624baaef360313c5e57633faf80a040e4b1",
    "shortSha": "7fc0762",
    "subject": "Meetups: live audio and video rooms, on LiveKit",
    "date": "2026-09-11T03:26:41+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "623ac4d3004a9993c5c318c7424878ed582eb63e",
    "shortSha": "623ac4d",
    "subject": "feat: later bookmark, person cards, and the files tab (#13)",
    "date": "2026-09-11T03:20:42+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "155e66fee81a86c31f7689309b4c5e81c1114649",
    "shortSha": "155e66f",
    "subject": "feat: skin tones in the picker, and search hit highlighting (#12)",
    "date": "2026-09-11T00:40:52+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "72eef658c21198002bbe18fefb677221b797f609",
    "shortSha": "72eef65",
    "subject": "feat: colon emoji autocomplete, toolbar link/list, XSS goldens (#11)",
    "date": "2026-09-10T21:36:31+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "6566ceb3f594772d2cf064c5a3a7e29d4e8b0a3d",
    "shortSha": "6566ceb",
    "subject": "feat: search from:/in:/has: without leftover words (#10)",
    "date": "2026-09-10T06:56:59+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7170a7a17deea9ce6ca42ef092699bcded268b46",
    "shortSha": "7170a7a",
    "subject": "feat: R4 activity_events, Mentions, unread around (#9)",
    "date": "2026-09-10T04:50:04+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "19d4c3cb30fb93f7a40430a11e5a77ae5d838d7c",
    "shortSha": "19d4c3c",
    "subject": "feat: R3 shell tabs, permalink path, last_reply_at index (#8)",
    "date": "2026-09-10T02:27:20+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "86a3d394f61910f26280ad63198c1c3ec40b1bb7",
    "shortSha": "86a3d39",
    "subject": "Finish R2 hardening and member quick wins (#7)",
    "date": "2026-09-09T19:54:16+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "912600181e2708ef9abc4ead2dc10a8c474c9181",
    "shortSha": "9126001",
    "subject": "fix: persist also-send-to-channel through the outbox, and show status (#4)",
    "date": "2026-09-09T15:49:56+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d2ecadf968e2286c2a954fceac95653664f5764d",
    "shortSha": "d2ecadf",
    "subject": "Put the account menu back in the corner, and stop the chat list leaving holes. (#5)",
    "date": "2026-09-09T15:30:01+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7b8c1c8f0c36775fdbe757411f4483f037694139",
    "shortSha": "7b8c1c8",
    "subject": "Refine the chat shell and harden live dashboard updates.",
    "date": "2026-09-08T17:49:30+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "83756c10fd1e887377291db0f764ef19b1e6633b",
    "shortSha": "83756c1",
    "subject": "Home is the dashboard, and settings stop pretending this is a grid of workspaces.",
    "date": "2026-09-08T17:45:57+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "fe69eebacab1050978f0212709935acd3c95763f",
    "shortSha": "fe69eeb",
    "subject": "Stop trusting a header the caller writes, and four more places a member reached too far",
    "date": "2026-09-07T00:07:53+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "55bafe08114487550b1900d28decb83ea70d6b31",
    "shortSha": "55bafe0",
    "subject": "Let your own assistant read this workspace, and say when a file cannot be uploaded",
    "date": "2026-09-06T18:23:49+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a8e0535eb4fa4b52d789bdaf2ca18779f422ea63",
    "shortSha": "a8e0535",
    "subject": "Say when a notification cannot reach anybody, and stop reporting failures as delivery",
    "date": "2026-09-06T14:17:48+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "bae5242ec1ca94b26c9695440f1045f8cb47aa07",
    "shortSha": "bae5242",
    "subject": "Images: a small copy for the channel, the original when you ask for it",
    "date": "2026-09-06T07:27:34+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "9d3b15366a65152f30c73e84acc80ec8a78ff2ab",
    "shortSha": "9d3b153",
    "subject": "Activity: everybody who named you, and everybody who reacted to what you wrote",
    "date": "2026-09-06T06:23:05+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a7e2da802c9a9790678ef65eef6b26dd8433495b",
    "shortSha": "a7e2da8",
    "subject": "A channel frame stops carrying your place in the channel; search learns time order",
    "date": "2026-09-06T04:41:39+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "47cac0bf47cb3038ccacf9c5077eb768c64b0acf",
    "shortSha": "47cac0b",
    "subject": "Summaries a model writes and you can check; questions that come back to whoever asked",
    "date": "2026-09-06T03:46:45+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1533f4ae5a6d0be40eb9285ac71b8afd45fd8f08",
    "shortSha": "1533f4a",
    "subject": "Record the trap that took the host down: two Coolify builds at once",
    "date": "2026-09-05T10:34:24+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "ab21354b54502d50e430b98b1339cdd0ae334f0a",
    "shortSha": "ab21354",
    "subject": "Work channels: a channel spun from a thread, with plan, changes and preview tabs",
    "date": "2026-09-05T09:48:36+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "cc35443bff34a0394e8deb2c4f470c041edc7535",
    "shortSha": "cc35443",
    "subject": "Put a Content-Security-Policy on every response",
    "date": "2026-09-05T07:13:45+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e4df5e80abe7d1fa21864318325bf6fd56791c6a",
    "shortSha": "e4df5e8",
    "subject": "Let a member connect their own agent, and let an agent remember",
    "date": "2026-09-05T05:20:04+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "097c1153e49c9c91ff4e269d7431b5188bd97300",
    "shortSha": "097c115",
    "subject": "Let agents answer each other, and let a person answer an agent",
    "date": "2026-09-05T04:48:55+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "645d2505faeccabb52665b176ced6c0c42340a07",
    "shortSha": "645d250",
    "subject": "Give an agent an owner, so a personal one is personal",
    "date": "2026-09-04T18:06:11+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a8556752f55f17b3380436df73adc2ce1375d218",
    "shortSha": "a855675",
    "subject": "Let a thread be left, and a channel be reopened",
    "date": "2026-09-04T13:30:48+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "40461d54fa369c170905914f2b0374422b6ccf4d",
    "shortSha": "40461d5",
    "subject": "Read the bits that were only ever written",
    "date": "2026-09-04T07:26:21+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "3a3efcfccd6b1aca5fa8445e758591fa01f790f9",
    "shortSha": "3a3efcf",
    "subject": "Rebuild the README, and make three of its claims true",
    "date": "2026-09-03T05:08:44+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1c4636df221e05e56413b39ca9ac469d204dbe81",
    "shortSha": "1c4636d",
    "subject": "Let the map catch up with the guide's parity test",
    "date": "2026-09-03T01:06:54+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "f9305d03ba7d6751465fcba651c373c2a05a7526",
    "shortSha": "f9305d0",
    "subject": "Answer \"how does this work?\" inside the app",
    "date": "2026-09-02T23:41:57+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "f48ec3a1d48fbf451816a5a1ce70033f1280fb6c",
    "shortSha": "f48ec3a",
    "subject": "Fix twenty-three defects an adversarial review found in today's work",
    "date": "2026-09-02T06:48:43+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5368213ea0e78a2cc2d47b7f2c031c6699437447",
    "shortSha": "5368213",
    "subject": "Add /remind, which is a scheduled message to yourself",
    "date": "2026-09-02T06:12:01+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "814a22f5cd5dc5f4e136942fbad70da29166720a",
    "shortSha": "814a22f",
    "subject": "Show the build card for what it knows",
    "date": "2026-09-02T05:49:15+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b8021dbb629a61c91c93f6a911bcec0858dbc9c3",
    "shortSha": "b8021db",
    "subject": "Make the build stamp survive a host with no repository",
    "date": "2026-09-02T05:36:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "29611cc05c9185cb2e6ed4638074d1ea54a48f02",
    "shortSha": "29611cc",
    "subject": "Walk the sidebar with ⌥↑ and ⌥↓, and stop a build stamp from blocking a deploy",
    "date": "2026-09-02T05:21:51+02:00",
    "author": "Marko Tiosavljevic"
  }
];
