/** Generated by `pnpm stamp`. Do not edit — see `scripts/stamp-commits.mjs`.
 *
 * The recent history, as source, so the "What's new" page can show it on a host that
 * builds from an exported tree with no repository in it. One commit behind by
 * construction: a commit cannot contain its own hash.
 */

import type { BuildCommit } from './buildInfo.ts';

export const GENERATED_REPO_URL = "https://github.com/magnetoid/blob";

export const GENERATED_COMMITS: readonly BuildCommit[] = [
  {
    "sha": "58be134b99d172624f971b1c163873040c97a918",
    "shortSha": "58be134b",
    "subject": "fix: keep each stack's Janus on its own network",
    "date": "2026-09-18T04:45:32+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e8c49f156fa3bf93ffd6e566ccec538fcb423644",
    "shortSha": "e8c49f15",
    "subject": "docs: the README says what Blob is, and shows it",
    "date": "2026-09-17T21:03:24+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "90aa14720659f903dc558b4951cc17f760a5a980",
    "shortSha": "90aa1472",
    "subject": "feat: the Janus page — a workspace configures its agent, a server configures Janus",
    "date": "2026-09-17T06:35:19+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "baaecf7b654aca269f6b3a62f3f8d5d9d40c9169",
    "shortSha": "baaecf7b",
    "subject": "feat: small motions — the client's small moments enter, leave and settle",
    "date": "2026-09-16T23:05:01+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d5efddee229cec45dc7d814d155af5a7b773a2e1",
    "shortSha": "d5efddee",
    "subject": "docs: three docstrings, said right",
    "date": "2026-09-16T16:01:26+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "86e0fcebcc10b6e0178b11b42d25ac457e52cf2c",
    "shortSha": "86e0fceb",
    "subject": "fix: the home view asks the resident agent, and the last words the review found",
    "date": "2026-09-16T15:52:37+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "88ea0aa6ebab15d4d1bc417eb199b68dcecc9aa3",
    "shortSha": "88ea0aa6",
    "subject": "docs: say where the model key is read, and tidy what the reviews left",
    "date": "2026-09-16T15:26:23+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5d02b43e3a394a88d77ac5a3597b48844d2c7f4b",
    "shortSha": "5d02b43e",
    "subject": "test: a mention in a channel founded after seeding is answered",
    "date": "2026-09-16T15:25:21+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "9353e046017ac88d31376a3d5826c6964fad0bc4",
    "shortSha": "9353e046",
    "subject": "docs: record that Blob ships no agent of its own",
    "date": "2026-09-16T03:57:03+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "f01289fcef54ad903d67eef9d2b8d16c98b0232b",
    "shortSha": "f01289fc",
    "subject": "feat: the home view asks whichever agent is here",
    "date": "2026-09-16T03:30:19+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2f70f14651f423f90b6dd30f761af3e136ec7ef9",
    "shortSha": "2f70f146",
    "subject": "refactor: fold the seeding loop back into the one seeder left",
    "date": "2026-09-16T03:09:55+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "9c75263ba6d47516550678e486e93f1b69a40db0",
    "shortSha": "9c75263b",
    "subject": "refactor: drop the agent-reads bound with the agent it bounded",
    "date": "2026-09-16T02:37:14+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "19eaae6b3799b6b3478faef96cc9e56292036569",
    "shortSha": "19eaae6b",
    "subject": "fix: say what the retirement really costs, and finish clearing what it left",
    "date": "2026-09-16T01:41:04+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1998b2af18e63fe5efab27994ce3d41d8a4fb138",
    "shortSha": "1998b2af",
    "subject": "feat: retire the agent Blob ran itself",
    "date": "2026-09-16T01:15:32+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "65f24b2faa94aae8842f9dd58676596f2840f5fd",
    "shortSha": "65f24b2f",
    "subject": "fix: keep the room's address to agents that can actually be reached",
    "date": "2026-09-15T23:54:39+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a74e951cd35875cbd4251a04dfcca5497ba9833f",
    "shortSha": "a74e951c",
    "subject": "feat: let a DM address a resident or owned agent without a mention",
    "date": "2026-09-15T23:41:40+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "17fdd848cd8c6005a1dd9161039c0a601c60746e",
    "shortSha": "17fdd848",
    "subject": "Design and plan the retirement of the agent Blob ran itself",
    "date": "2026-09-15T23:01:52+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d3eb5bf92a4db984836709f610ef3799be65a433",
    "shortSha": "d3eb5bf9",
    "subject": "Design the Janus page in the instance console",
    "date": "2026-09-15T22:36:17+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1d424d73af703567ee668b4853b17d5529cc8a24",
    "shortSha": "1d424d73",
    "subject": "Put the seeded agents into a public channel the moment it is founded",
    "date": "2026-09-15T22:27:17+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "67567c34e98c68ba27825baf54f52602a27f4098",
    "shortSha": "67567c34",
    "subject": "Give the two agent seeders one loop and one joiner",
    "date": "2026-09-15T20:17:29+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "c741989c83f67bb56964743d5d62d344894b2f07",
    "shortSha": "c741989c",
    "subject": "Stop claiming two env vars configure the agent when they do not",
    "date": "2026-09-15T14:02:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2c4b182b8c15c6e210fd884fc4057d7af6248f0b",
    "shortSha": "2c4b182b",
    "subject": "Fall back a blank JANUS_AGENT_NAME to \"Janus\" instead of \"\"",
    "date": "2026-09-15T03:22:02+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "61b81a7cb4b2a384b369058fcc10a342cf6074c0",
    "shortSha": "61b81a7c",
    "subject": "Give the app and the worker the settings they were promised",
    "date": "2026-09-15T03:08:45+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "90f2fa719de9ab58c9a1373adbc681d8d72ad0ff",
    "shortSha": "90f2fa71",
    "subject": "Seed Janus into the rooms, and only onto our own row",
    "date": "2026-09-15T03:08:33+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "947673e6273a39e0bbaeeb4ba429d1ff7a601214",
    "shortSha": "947673e6",
    "subject": "Map the module the agent seeding lives in",
    "date": "2026-09-15T02:45:37+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d631aa0fe13468166813a8bdfb2d01f8ab32a00d",
    "shortSha": "d631aa0f",
    "subject": "Run Janus as a service in this stack, off unless asked for",
    "date": "2026-09-15T02:37:42+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "82d8a96f19f56123c1497e490815a4b1e314c48d",
    "shortSha": "82d8a96f",
    "subject": "Pin that both guards refuse internal agent URLs",
    "date": "2026-09-15T02:22:34+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e711a6e01908123372d30d0d67e96a1fe27ad720",
    "shortSha": "e711a6e0",
    "subject": "Pin that an internal agent URL is still refused from a route",
    "date": "2026-09-15T02:16:13+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "576af177e66316de89439d023976fd6bcdb32a5b",
    "shortSha": "576af177",
    "subject": "Reconcile Janus at boot, the way the built-in agent is reconciled",
    "date": "2026-09-15T02:08:20+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2cd4d4f6a5a574d9e120cf526bbd22e354c2bfcd",
    "shortSha": "2cd4d4f6",
    "subject": "Move an already-installed Janus onto the internal address",
    "date": "2026-09-15T01:54:31+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b0646b0880aab82b4fa4557ef5762447b22e9955",
    "shortSha": "b0646b08",
    "subject": "Seed Janus into a workspace when it is running beside us",
    "date": "2026-09-15T01:42:47+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1ff60088880a4e988d23d75af8f2a83060d01950",
    "shortSha": "1ff60088",
    "subject": "Let an install be given the secret it must share",
    "date": "2026-09-15T01:18:34+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "728d79933fdb3b20dd4acc87812adf09d1f45d90",
    "shortSha": "728d7993",
    "subject": "Let the environment say Janus is running beside us",
    "date": "2026-09-15T01:04:38+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "05bebafb938aa98545b26c2f805fa9cf2c86c91d",
    "shortSha": "05bebafb",
    "subject": "Plan: Janus as a service in Blob's stack, phase 1",
    "date": "2026-09-15T00:28:39+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "ff087e29edb3b41ab0cc788d0b7014ff54cbdd25",
    "shortSha": "ff087e29",
    "subject": "Design: Janus as a service in Blob's own stack, not a Coolify app",
    "date": "2026-09-14T23:30:09+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1d514892699b66e1f1471cb7207d8686c577143f",
    "shortSha": "1d514892",
    "subject": "Say in 0018 that Blob and Janus are two agents, not one",
    "date": "2026-09-14T23:21:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "c25c72ff3309fb44953934340a075e0bd3323af3",
    "shortSha": "c25c72ff",
    "subject": "Record what the two kinds of agent are, and stop defaulting to a model DeepSeek retired",
    "date": "2026-09-14T23:08:26+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "eed1cdd1d4a201d7f68405033bdb6867c4a6d416",
    "shortSha": "eed1cdd1",
    "subject": "Write down what the agent sidebar taught, before it is forgotten",
    "date": "2026-09-14T22:04:32+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1f8df24ac0d4632f7d80e0865f08a6c476be685c",
    "shortSha": "1f8df24a",
    "subject": "Stop offering an agent whose app is switched off",
    "date": "2026-09-14T21:55:10+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "156284192fde53c92fec7775ffe6465761752d6c",
    "shortSha": "15628419",
    "subject": "Stop the sidebar naming agents that were uninstalled",
    "date": "2026-09-14T21:23:43+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "4dff8e548666cfb08ae271b84a24f03c9fe33cd5",
    "shortSha": "4dff8e54",
    "subject": "Stop a channel with unread swallowing the message you just sent",
    "date": "2026-09-14T20:35:19+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "be555db0e6e1cc4424b8b78c4ab16dd8fc4db657",
    "shortSha": "be555db0",
    "subject": "Stop a channel switch leaving the old message list in the document",
    "date": "2026-09-14T18:43:23+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "81310e6a07563d2e754b4fb535984b9097ce69fe",
    "shortSha": "81310e6a",
    "subject": "Put members, user groups, invitations and accounts on one page",
    "date": "2026-09-14T05:16:05+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7540d2e0faa6c694c8305d870ad0087d9e0468fc",
    "shortSha": "7540d2e0",
    "subject": "Rebuild the agents console to Meadow 2c, and stop teaching the bridge to Janus",
    "date": "2026-09-14T04:59:31+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b2edb9153ccd05d762c0a46e984eaf62bb4e524f",
    "shortSha": "b2edb915",
    "subject": "Give the agents console the three numbers its table needs",
    "date": "2026-09-14T04:49:40+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "ac126a69339a0b9d468d7984852744ea0b1c6ac5",
    "shortSha": "ac126a69",
    "subject": "Let the gate accept the readiness body it now serves",
    "date": "2026-09-14T04:42:10+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "c173f327bcac26b3a74f3e452a225ad19c5d1c78",
    "shortSha": "c173f327",
    "subject": "Make the deploy job read what shipped instead of trusting its own 200",
    "date": "2026-09-14T04:29:24+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "0955008dc535d65bafee3b986f3b8353ae2ee82a",
    "shortSha": "0955008d",
    "subject": "Say that Blob organises work, and enforce the rule that was only prose",
    "date": "2026-09-14T03:48:18+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e36703097d0e78bdc0abb63c72e34a0750de4816",
    "shortSha": "e3670309",
    "subject": "Give the smallest actions something to say back",
    "date": "2026-09-14T03:42:49+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "69afb50b7e9f569967cf2bac09f4dadb1bb31569",
    "shortSha": "69afb50b",
    "subject": "Make ⌘K find what was said, not just where to go",
    "date": "2026-09-14T03:35:40+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5029c37e7137592e702420335c9b29bdc2739c7e",
    "shortSha": "5029c37e",
    "subject": "Put the workspace above the whole app, and give the chrome its space back",
    "date": "2026-09-14T03:28:38+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b86ff397a40fd2b5915fc18a1f4fea55763695f2",
    "shortSha": "b86ff397",
    "subject": "Stop a deleted message stranding the channel's tail pointer",
    "date": "2026-09-14T03:28:24+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a6e80f48e693fa373d0283fbfc0fd30b81f6f7d9",
    "shortSha": "a6e80f48",
    "subject": "Stop a test measuring the calendar instead of the page",
    "date": "2026-09-14T03:26:08+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "75dc9a4988b97aa8dae46d25c5e52ae72481a451",
    "shortSha": "75dc9a49",
    "subject": "Let ADR 0003's rule be written down in the file it governs",
    "date": "2026-09-14T00:30:35+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5e30253f51166fdbc1eb210230cac752ae3bf63e",
    "shortSha": "5e30253f",
    "subject": "Map the voice attachment migration and its tests",
    "date": "2026-09-13T23:53:50+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "56873ca01122a292ef9c779237d0aaac5a799a45",
    "shortSha": "56873ca0",
    "subject": "Give the releases version numbers, and this one a name",
    "date": "2026-09-13T23:51:59+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "8632627d5c1fe816e06c97155b13e709622d35ea",
    "shortSha": "8632627d",
    "subject": "Notice a connection that has quietly died",
    "date": "2026-09-13T23:49:57+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "72c7b417f840ee60f0986bbf1eefd7dbc1a4ebe8",
    "shortSha": "72c7b417",
    "subject": "Give an attachment the shape a voice message needs",
    "date": "2026-09-13T23:47:09+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "17f09f25014e39e7fb05e5d39949442606d84d18",
    "shortSha": "17f09f25",
    "subject": "Describe the deploy path that now exists",
    "date": "2026-09-13T21:31:34+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e42ca5ce15eec0c2afd82c7313ba8b0071583adf",
    "shortSha": "e42ca5ce",
    "subject": "Deploy from the gate instead of from the push",
    "date": "2026-09-13T21:23:27+02:00",
    "author": "Marko Tiosavljevic"
  }
];
