/** Generated by `pnpm stamp`. Do not edit — see `scripts/stamp-commits.mjs`.
 *
 * The recent history, as source, so the "What's new" page can show it on a host that
 * builds from an exported tree with no repository in it. One commit behind by
 * construction: a commit cannot contain its own hash.
 */

import type { BuildCommit } from './buildInfo.ts';

export const GENERATED_REPO_URL = "https://github.com/magnetoid/blob";

export const GENERATED_COMMITS: readonly BuildCommit[] = [
  {
    "sha": "e19bf9b807dc5c5723a54be81797a9f10c1e3b2a",
    "shortSha": "e19bf9b8",
    "subject": "feat: the @ picker puts who you tagged last first; a finished run is a quiet line — 1.6.0",
    "date": "2026-09-22T15:51:06+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a49257b2ec306d2feb02fc476014ed7fdd7c958c",
    "shortSha": "a49257b2",
    "subject": "feat: the admin and settings pages use the width, in cards — 1.5.0",
    "date": "2026-09-22T15:03:49+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "9abb2ae8ff68618ff4ae14229ebcb94b8759ebae",
    "shortSha": "9abb2ae8",
    "subject": "feat: small things answer — dialogs leave, arrivals rise, presses give — 1.4.0",
    "date": "2026-09-22T14:43:18+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d0db9ae55276d28cb499ac8495032f091de4c785",
    "shortSha": "d0db9ae5",
    "subject": "feat: the workspace mark folds the channel list — 1.3.0",
    "date": "2026-09-22T04:17:07+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b99e85b8004f4a90a0cdacfee96ab0edcfa4523a",
    "shortSha": "b99e85b8",
    "subject": "fix: the new-messages bar leaves once the new messages have been seen",
    "date": "2026-09-22T04:16:50+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7f3d74569e47529a4186d8baaadf7ff2da84ff03",
    "shortSha": "7f3d7456",
    "subject": "chore: pin Janus 0.18.0, which hands Blob the files a reply names",
    "date": "2026-09-22T00:03:09+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "178ef4fa9b92e6d3404debbdfb3a6dd13f42258d",
    "shortSha": "178ef4fa",
    "subject": "fix: a file's type does not depend on which Python the server runs",
    "date": "2026-09-21T23:52:16+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "4e20d421c591a56800853d7bfc62219f362fd255",
    "shortSha": "4e20d421",
    "subject": "feat: agents hand over files, and a file opens beside the conversation",
    "date": "2026-09-21T23:41:00+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7cc58b6ca58a10402234701dca7ef1d904c5af0f",
    "shortSha": "7cc58b6c",
    "subject": "feat: harden themes and compositor motion",
    "date": "2026-09-19T02:53:42+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d45a398802362732eba44fb13a5e60c2fa661157",
    "shortSha": "d45a3988",
    "subject": "feat: /search carries the scope it was opened with",
    "date": "2026-09-18T07:07:37+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e3f7ae7ce017e10aca2118091d3dce0f6208d661",
    "shortSha": "e3f7ae7c",
    "subject": "fix: keep the keyboard up, name the scope control, and pin ⌘K's two requests",
    "date": "2026-09-18T06:36:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2b4c4cc1bb94f8e01e263be09a4b1a457e5e6c1b",
    "shortSha": "2b4c4cc1",
    "subject": "feat: ⌘K in four sections, with Tab to narrow",
    "date": "2026-09-18T06:17:13+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "f099f7e97feafe7006c280e3b24f1046e79df1a9",
    "shortSha": "f099f7e9",
    "subject": "feat: filter the files library by filename",
    "date": "2026-09-18T05:46:27+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "bb172ae76eba40a491ac21f017a9db1a6529553b",
    "shortSha": "bb172ae7",
    "subject": "docs: search scopes in ⌘K — spec and plan",
    "date": "2026-09-18T05:26:11+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "76698c47624a3c6e34af7c8e91b76ca0848a5713",
    "shortSha": "76698c47",
    "subject": "chore: pin Janus 0.17.1, which redacts the config file at the source",
    "date": "2026-09-18T05:07:04+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "ca24e90a863a6277099c0ed601277bc75885c27f",
    "shortSha": "ca24e90a",
    "subject": "feat: the channel list starts at the top — 1.2.1",
    "date": "2026-09-18T05:05:05+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "58be134b99d172624f971b1c163873040c97a918",
    "shortSha": "58be134b",
    "subject": "fix: keep each stack's Janus on its own network",
    "date": "2026-09-18T04:45:32+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e8c49f156fa3bf93ffd6e566ccec538fcb423644",
    "shortSha": "e8c49f15",
    "subject": "docs: the README says what Blob is, and shows it",
    "date": "2026-09-17T21:03:24+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "90aa14720659f903dc558b4951cc17f760a5a980",
    "shortSha": "90aa1472",
    "subject": "feat: the Janus page — a workspace configures its agent, a server configures Janus",
    "date": "2026-09-17T06:35:19+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "baaecf7b654aca269f6b3a62f3f8d5d9d40c9169",
    "shortSha": "baaecf7b",
    "subject": "feat: small motions — the client's small moments enter, leave and settle",
    "date": "2026-09-16T23:05:01+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d5efddee229cec45dc7d814d155af5a7b773a2e1",
    "shortSha": "d5efddee",
    "subject": "docs: three docstrings, said right",
    "date": "2026-09-16T16:01:26+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "86e0fcebcc10b6e0178b11b42d25ac457e52cf2c",
    "shortSha": "86e0fceb",
    "subject": "fix: the home view asks the resident agent, and the last words the review found",
    "date": "2026-09-16T15:52:37+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "88ea0aa6ebab15d4d1bc417eb199b68dcecc9aa3",
    "shortSha": "88ea0aa6",
    "subject": "docs: say where the model key is read, and tidy what the reviews left",
    "date": "2026-09-16T15:26:23+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "5d02b43e3a394a88d77ac5a3597b48844d2c7f4b",
    "shortSha": "5d02b43e",
    "subject": "test: a mention in a channel founded after seeding is answered",
    "date": "2026-09-16T15:25:21+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "9353e046017ac88d31376a3d5826c6964fad0bc4",
    "shortSha": "9353e046",
    "subject": "docs: record that Blob ships no agent of its own",
    "date": "2026-09-16T03:57:03+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "f01289fcef54ad903d67eef9d2b8d16c98b0232b",
    "shortSha": "f01289fc",
    "subject": "feat: the home view asks whichever agent is here",
    "date": "2026-09-16T03:30:19+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2f70f14651f423f90b6dd30f761af3e136ec7ef9",
    "shortSha": "2f70f146",
    "subject": "refactor: fold the seeding loop back into the one seeder left",
    "date": "2026-09-16T03:09:55+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "9c75263ba6d47516550678e486e93f1b69a40db0",
    "shortSha": "9c75263b",
    "subject": "refactor: drop the agent-reads bound with the agent it bounded",
    "date": "2026-09-16T02:37:14+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "19eaae6b3799b6b3478faef96cc9e56292036569",
    "shortSha": "19eaae6b",
    "subject": "fix: say what the retirement really costs, and finish clearing what it left",
    "date": "2026-09-16T01:41:04+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1998b2af18e63fe5efab27994ce3d41d8a4fb138",
    "shortSha": "1998b2af",
    "subject": "feat: retire the agent Blob ran itself",
    "date": "2026-09-16T01:15:32+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "65f24b2faa94aae8842f9dd58676596f2840f5fd",
    "shortSha": "65f24b2f",
    "subject": "fix: keep the room's address to agents that can actually be reached",
    "date": "2026-09-15T23:54:39+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "a74e951cd35875cbd4251a04dfcca5497ba9833f",
    "shortSha": "a74e951c",
    "subject": "feat: let a DM address a resident or owned agent without a mention",
    "date": "2026-09-15T23:41:40+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "17fdd848cd8c6005a1dd9161039c0a601c60746e",
    "shortSha": "17fdd848",
    "subject": "Design and plan the retirement of the agent Blob ran itself",
    "date": "2026-09-15T23:01:52+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d3eb5bf92a4db984836709f610ef3799be65a433",
    "shortSha": "d3eb5bf9",
    "subject": "Design the Janus page in the instance console",
    "date": "2026-09-15T22:36:17+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1d424d73af703567ee668b4853b17d5529cc8a24",
    "shortSha": "1d424d73",
    "subject": "Put the seeded agents into a public channel the moment it is founded",
    "date": "2026-09-15T22:27:17+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "67567c34e98c68ba27825baf54f52602a27f4098",
    "shortSha": "67567c34",
    "subject": "Give the two agent seeders one loop and one joiner",
    "date": "2026-09-15T20:17:29+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "c741989c83f67bb56964743d5d62d344894b2f07",
    "shortSha": "c741989c",
    "subject": "Stop claiming two env vars configure the agent when they do not",
    "date": "2026-09-15T14:02:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2c4b182b8c15c6e210fd884fc4057d7af6248f0b",
    "shortSha": "2c4b182b",
    "subject": "Fall back a blank JANUS_AGENT_NAME to \"Janus\" instead of \"\"",
    "date": "2026-09-15T03:22:02+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "61b81a7cb4b2a384b369058fcc10a342cf6074c0",
    "shortSha": "61b81a7c",
    "subject": "Give the app and the worker the settings they were promised",
    "date": "2026-09-15T03:08:45+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "90f2fa719de9ab58c9a1373adbc681d8d72ad0ff",
    "shortSha": "90f2fa71",
    "subject": "Seed Janus into the rooms, and only onto our own row",
    "date": "2026-09-15T03:08:33+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "947673e6273a39e0bbaeeb4ba429d1ff7a601214",
    "shortSha": "947673e6",
    "subject": "Map the module the agent seeding lives in",
    "date": "2026-09-15T02:45:37+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "d631aa0fe13468166813a8bdfb2d01f8ab32a00d",
    "shortSha": "d631aa0f",
    "subject": "Run Janus as a service in this stack, off unless asked for",
    "date": "2026-09-15T02:37:42+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "82d8a96f19f56123c1497e490815a4b1e314c48d",
    "shortSha": "82d8a96f",
    "subject": "Pin that both guards refuse internal agent URLs",
    "date": "2026-09-15T02:22:34+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "e711a6e01908123372d30d0d67e96a1fe27ad720",
    "shortSha": "e711a6e0",
    "subject": "Pin that an internal agent URL is still refused from a route",
    "date": "2026-09-15T02:16:13+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "576af177e66316de89439d023976fd6bcdb32a5b",
    "shortSha": "576af177",
    "subject": "Reconcile Janus at boot, the way the built-in agent is reconciled",
    "date": "2026-09-15T02:08:20+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "2cd4d4f6a5a574d9e120cf526bbd22e354c2bfcd",
    "shortSha": "2cd4d4f6",
    "subject": "Move an already-installed Janus onto the internal address",
    "date": "2026-09-15T01:54:31+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "b0646b0880aab82b4fa4557ef5762447b22e9955",
    "shortSha": "b0646b08",
    "subject": "Seed Janus into a workspace when it is running beside us",
    "date": "2026-09-15T01:42:47+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1ff60088880a4e988d23d75af8f2a83060d01950",
    "shortSha": "1ff60088",
    "subject": "Let an install be given the secret it must share",
    "date": "2026-09-15T01:18:34+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "728d79933fdb3b20dd4acc87812adf09d1f45d90",
    "shortSha": "728d7993",
    "subject": "Let the environment say Janus is running beside us",
    "date": "2026-09-15T01:04:38+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "05bebafb938aa98545b26c2f805fa9cf2c86c91d",
    "shortSha": "05bebafb",
    "subject": "Plan: Janus as a service in Blob's stack, phase 1",
    "date": "2026-09-15T00:28:39+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "ff087e29edb3b41ab0cc788d0b7014ff54cbdd25",
    "shortSha": "ff087e29",
    "subject": "Design: Janus as a service in Blob's own stack, not a Coolify app",
    "date": "2026-09-14T23:30:09+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1d514892699b66e1f1471cb7207d8686c577143f",
    "shortSha": "1d514892",
    "subject": "Say in 0018 that Blob and Janus are two agents, not one",
    "date": "2026-09-14T23:21:28+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "c25c72ff3309fb44953934340a075e0bd3323af3",
    "shortSha": "c25c72ff",
    "subject": "Record what the two kinds of agent are, and stop defaulting to a model DeepSeek retired",
    "date": "2026-09-14T23:08:26+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "eed1cdd1d4a201d7f68405033bdb6867c4a6d416",
    "shortSha": "eed1cdd1",
    "subject": "Write down what the agent sidebar taught, before it is forgotten",
    "date": "2026-09-14T22:04:32+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "1f8df24ac0d4632f7d80e0865f08a6c476be685c",
    "shortSha": "1f8df24a",
    "subject": "Stop offering an agent whose app is switched off",
    "date": "2026-09-14T21:55:10+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "156284192fde53c92fec7775ffe6465761752d6c",
    "shortSha": "15628419",
    "subject": "Stop the sidebar naming agents that were uninstalled",
    "date": "2026-09-14T21:23:43+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "4dff8e548666cfb08ae271b84a24f03c9fe33cd5",
    "shortSha": "4dff8e54",
    "subject": "Stop a channel with unread swallowing the message you just sent",
    "date": "2026-09-14T20:35:19+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "be555db0e6e1cc4424b8b78c4ab16dd8fc4db657",
    "shortSha": "be555db0",
    "subject": "Stop a channel switch leaving the old message list in the document",
    "date": "2026-09-14T18:43:23+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "81310e6a07563d2e754b4fb535984b9097ce69fe",
    "shortSha": "81310e6a",
    "subject": "Put members, user groups, invitations and accounts on one page",
    "date": "2026-09-14T05:16:05+02:00",
    "author": "Marko Tiosavljevic"
  },
  {
    "sha": "7540d2e0faa6c694c8305d870ad0087d9e0468fc",
    "shortSha": "7540d2e0",
    "subject": "Rebuild the agents console to Meadow 2c, and stop teaching the bridge to Janus",
    "date": "2026-09-14T04:59:31+02:00",
    "author": "Marko Tiosavljevic"
  }
];
